export const getRandomBackground = () => backgrounds[Math.floor(Math.random() * 31)];

export const backgrounds = [
	'./ring-background/0.jpg',
	'./ring-background/1.jpg',
	'./ring-background/2.jpg',
	'./ring-background/3.jpg',
	'./ring-background/4.jpg',
	'./ring-background/5.jpg',
	'./ring-background/6.jpg',
	'./ring-background/7.jpg',
	'./ring-background/8.jpg',
	'./ring-background/9.jpg',
	'./ring-background/10.jpg',
	'./ring-background/11.jpg',
	'./ring-background/12.jpg',
	'./ring-background/13.jpg',
	'./ring-background/14.jpg',
	'./ring-background/15.jpg',
	'./ring-background/16.jpg',
	'./ring-background/17.jpg',
	'./ring-background/19.jpg',
	'./ring-background/19.jpg',
	'./ring-background/20.jpg',
	'./ring-background/21.jpg',
	'./ring-background/22.jpg',
	'./ring-background/23.jpg',
	'./ring-background/24.jpg',
	'./ring-background/25.jpg',
	'./ring-background/26.jpg',
	'./ring-background/27.jpg',
	'./ring-background/28.jpg',
	'./ring-background/29.jpg',
	'./ring-background/30.jpg',
	'./ring-background/31.jpg'
]
/* export const backgrounds= {
	[0]: './0.jpg',
	[1]: './1.jpg',
	[2]: './2.jpg',
	[3]: './3.jpg',
	[4]: './4.jpg',
	[5]: './5.jpg',
	[6]: './6.jpg',
	[7]: './7.jpg',
	[8]: './8.jpg',
	[9]: './9.jpg',
	[10]: './10.jpg',
	[11]: './11.jpg',
	[12]: './12.jpg',
	[13]: './13.jpg',
	[14]: './14.jpg',
	[15]: './15.jpg',
	[16]: './16.jpg',
	[17]: './17.jpg',
	[18]: './19.jpg',
	[19]: './19.jpg',
	[20]: './20.jpg',
	[21]: './21.jpg',
	[22]: './22.jpg'
} */